"""message

Revision ID: 55edbb7c009a
Revises: 899f71b07e66
Create Date: 2025-03-21 13:21:00.328874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55edbb7c009a'
down_revision = '899f71b07e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
